# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()
config.bind('<Ctrl-m>', 'open -t http://www.gmail.com')
config.bind('J', 'tab-prev')
config.bind('K', 'tab-next')
config.bind('u', 'scroll-page 0 -0.5')
config.bind('d', 'scroll-page 0 0.5')
config.bind('x', 'tab-close')
config.bind('X', 'undo')
config.bind('m', 'hint links spawn mpv {hint-url}')
config.bind('t', 'set-cmd-text -s :open -t')
config.bind('O', 'set-cmd-text :open {url:pretty}')
config.bind('M', 'spawn mpv {url}')
config.bind('cr', 'config-source')
config.bind('<Ctrl-k>', 'command-history-prev', mode='command')
config.bind('<Ctrl-j>', 'command-history-next', mode='command')
config.bind('cr', 'config-source')
config.bind('gi', 'hint inputs')
config.bind('D', 'download-open ;; download-remove')
config.bind('<Ctrl-t>', 'tab-pin')
config.bind('<Ctrl-i>', 'spawn --userscript qute-pass --dmenu-invocation dmenu')
config.bind('<Ctrl-p>', 'spawn --userscript qute-pass --dmenu-invocation dmenu --password-only')
config.bind('<Ctrl-w>', 'download')

c.url.searchengines = {'DEFAULT': 'https://google.com/search?q={}',
        'y': 'http://www.youtube.com/results?search_query={}',
        'm': 'https://www.google.com/maps?q={}',
        'a': 'http://www.amazon.com/s/?field-keywords={}',
        'aw': 'https://wiki.archlinux.org/?search={}',
        'w': 'http://en.wikipedia.org/w/index.php?title=Special:Search&search={}'}
c.url.default_page = ('about:blank')

c.editor.command = ['st', '-f', 'Terminus:size=10:antialias=false:autohint=false', '-e', 'vim', '{}']
c.auto_save.session = True

c.downloads.location.directory = ('~/Downloads')
c.downloads.location.prompt = False

c.hints.next_regexes.append(r'\B›\B')
c.hints.prev_regexes.append(r'\B‹\B')
c.hints.chars = ('asdfghjklqwertyuiopzxcvbnm')
c.content.geolocation = True
c.tabs.background = True
c.messages.timeout = 5000
c.input.insert_mode.auto_load = True
c.scrolling.bar = True

# requires `sudo /usr/share/qutebrowser/scripts/dictcli.py install en-US` be run first
c.spellcheck.languages = ['en-US']
