#!/bin/sh

# bspwm settings
bspc monitor --reset-desktops I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

#gruvbox dark green
bspc config focused_border_color "#98971a"

# Rules
bspc rule --add Chromium desktop='^10'
bspc rule --add Chromium-browser desktop='^10'
bspc rule --add Zathura state=tiled
# LibreOffice always tiled
bspc rule --add '*:soffice' state=tiled

# Set cursor to arrow
xsetroot -cursor_name left_ptr

# Startup program(s)
st -f "Terminus:size=10" -e tmux &
