# Typical laptop setup, with wifi, brightness, battery etc, for Sway.
#
bg_default: &bg_default {stack: [{background: {color: 81A1C1ff}}, {underline: {size: 4, color: D8DEE9ff}}]}

std_underline: &std_underline {underline: { size: 2, color: ff0000ff}}

# This is THE bar configuration
bar:
  font: terminus:size=14

  height: 20
  location: top
  spacing: 5
  margin: 7

  foreground: ffffffff
  background: 111111cc

  left:
    - river:
        anchors:
          - base: &river_base
              left-margin: 10
              right-margin: 13 
              default: {string: {text: "0"}}
              conditions:
                id == 1: {string: {text: "1"}}  
                id == 2: {string: {text: "2"}}  
                id == 3: {string: {text: "3"}}  
                id == 4: {string: {text: "4"}}  
                id == 5: {string: {text: "5"}}  
                id == 10: {string: {text: "scratchpad"}}  
                id == 11: {string: {text: "work"}}  

        content:
          map:
            on-click: 
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            conditions:
              state == urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: D08770ff}}
              state == focused:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == visible && ~occupied:
                map:
                  <<: *river_base
              state == visible && occupied:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == unfocused:
                map:
                  <<: *river_base
              state == invisible && ~occupied: {empty: {}}
              state == invisible && occupied:
                map:
                  <<: *river_base
                  deco: {underline: {size: 3, color: ea6962ff}}

    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                - string: {text: "{app-id}", foreground: ffa0a0ff}
                - string: {text: ": {title}"}
  right:
    - network:
        content:
          map:
            conditions:
              carrier:
                map:
                  conditions:
                    state == up && ipv4 != "" && ssid != "": {string: {text: "[{ssid}:▲]"}}
                    state == up && ipv4 != "": {string: {text: "[{name}:▲]"}}
    - battery:
        name: BAT0
        poll-interval: 30000
        anchors:
          discharging: &discharging
            list:
              items:
                - string: {text: "▼{capacity}% {estimate}"}
        content:
          map:
            conditions:
              state == unknown:
                - string: {text: "▼{capacity}% {estimate}"}
              state == discharging:
                - string: {text: "▼{capacity}% {estimate}"}
              state == charging:
                - string: {text: "▲{capacity}% {estimate}"}
              state == full:
                - string: {text: "▲{capacity}% full"}
              state == "not charging":
                - string: {text: "▲{capacity}%"}

    - pipewire:
        anchors:
          volume: &volume
            conditions:
              muted: {string: {text: "[♫:{linear_volume}%]", foreground: ff0000ff}}
              ~muted: {string: {text: "[♫:{linear_volume}%]"}}
        content:
          map:
            conditions:
              type == "sink":
                map:
                  <<: *volume
    - clock:
        time-format: "%H:%M"
        content:
          - string: {text: "{date}", right-margin: 5}
          - string: {text: "{time}"}
