#!/bin/sh

# needed for xdg-desktop-portals to work, otherwise, can lead to timeouts
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
systemctl --user restart xdg-desktop-portal

# Autostart
autostart() {
	prog="$1"
	shift 1

	killall -q "$prog"
	riverctl spawn "$prog" "$@"
}

exec_once() {
  if ! pgrep -u "$USER" -x "$1" > /dev/null
  then
    echo "$0: No '$1' found, starting it."
    riverctl spawn "$@"
  fi
}

# start an instance of foot
riverctl map normal Super Return spawn foot

# Super+Q to close the focused view
riverctl map normal Super Q close

# exit river
riverctl map normal Super+Shift Q exit

# Immediately trigger swayidle timeout (lock and turn off monitor)
riverctl map normal Super BackSpace spawn 'wlopm --off \"*\" && sleep 0.5 && killall -SIGUSR1 swayidle'

# screenshot to clipboard
riverctl map normal Super S spawn 'grim -g "$(slurp -d)" - | wl-copy'

# open fuzzel
riverctl map normal Super F spawn 'fuzzel --font terminus:weight=bold:size=12'

# toggle mpc
riverctl map normal Super C spawn 'mpc toggle'

# focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# swap the focused view with the next/previous view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# bump the focused view to the top of the layout stack
riverctl map normal Super A zoom

# decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# move views
riverctl map-pointer normal Super BTN_LEFT move-view

# resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

# Tags: use only 4 tags, mapped to y u i o => tags 1..4
for key_i in 0 1 2 3
do
    case "$key_i" in
        0) key=y ;;
        1) key=u ;;
        2) key=i ;;
        3) key=o ;;
    esac

    tags=$((1 << key_i))

    # focus tag [1-4]
    riverctl map normal Super "$key" set-focused-tags $tags

    # tag focused view with tag [1-4]
    riverctl map normal Super+Shift "$key" set-view-tags $tags

    # toggle focus of tag [1-4]
    riverctl map normal Super+Control "$key" toggle-focused-tags $tags

    # toggle tag [1-4] of focused view
    riverctl map normal Super+Shift+Control "$key" toggle-view-tags $tags
done

# all tags (same as tags 1-4 combined)
all_tags=$(((1 << 4) - 1))

# focus all tags
riverctl map normal Super p set-focused-tags $all_tags

# tag focused view with all tags
riverctl map normal Super+Shift p set-view-tags $all_tags

# focus view on previous tag
riverctl map normal Super W focus-previous-tags

# toggle float
riverctl map normal Super T toggle-float

# toggle fullscreen
riverctl map normal Super Z toggle-fullscreen

# Various media key mapping examples for both normal and locked mode 
for mode in normal locked
do
    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 2'
    riverctl map $mode Super equal spawn 'pamixer -i 2'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 2'
    riverctl map $mode Super minus spawn 'pamixer -d 2'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'
    riverctl map $mode Super m spawn 'pamixer --toggle-mute'

    # Control screen backlight brightness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x364c53
riverctl border-width 4

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 &

# set keyboard remaps, capslock to ctrl, printscreen to win
riverctl keyboard-layout -options "caps:ctrl_modifier,altwin:prtsc_rwin" "us"

riverctl focus-follows-cursor always

# screen idle and lock. sleep on resume is for handling kvm switch "delay"
exec_once "swayidle -w \
    timeout 1200 'waylock -fork-on-lock' \
    timeout 1230 'systemctl suspend' \
    before-sleep 'waylock -fork-on-lock'"

autostart waybar
autostart kanshi
exec_once mpd

# start foot w/ tmux
exec_once "foot tmux"
